language: go

branches:
  only:
    - master
    - develop
    - feature/*
    - release/*
    - hotfix/*
    - bugfix/*

os:
  - linux
  - osx

go:
  - "1.14"

env:
  - GO111MODULE=on

install:
  - curl https://cdn.shiftleft.io/download/sl > sl && sudo mv sl /usr/local/bin/  && sudo chmod a+rx /usr/local/bin/sl
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin latest
  - sl auth --org $SHIFTLEFT_ORG_ID --token $SHIFTLEFT_ACCESS_TOKEN --no-diagnostic

stages:
  - Build
  - Test

jobs:
  include:
    - stage: Build
      script:
        - make build

    - stage: Test
      name: Code Quality Tests
      script:
        - golangci-lint run

    - stage: Test
      name: Unit Tests
      script:
        - make test

    - stage: test
      name: Vulnerabilty Analysis
      script:
        - sl analyze --wait --tag branch=$TRAVIS_BRANCH --tag app.group=MyLabs --tag app.language=go --app MyLabs-G0 --cpg --go ./...
