language: go

branches:
  only:
    - master
    - dev
    - release/*

os:
  - linux
  - osx

go:
  - "1.13"
  - "1.14"

env:
  - GO111MODULE=on

install:
  - sudo curl https://cdn.shiftleft.io/download/sl > /usr/local/bin/sl && sudo chmod a+rx /usr/local/bin/sl
  - sudo curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.24.0

after_install:
  - sl auth --org "SHIFTLEFT_ORG_ID" --token "SHIFTLEFT_ACCESS_TOKEN"

script:
  - golangci-lint run
  - go test -v ./...
  - sl analyze --wait --tag branch=$TRAVIS_BRANCH --tag app.group=MyLabs --tag app.language=go --app MyLabs-G0 --cpg --go ./...

gobuild_args: -o mylabs-go
