# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

variables:
  GOPATH: '$(Pipeline.Workspace)/gowork'

stages:
  - stage: Build
    jobs:
      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Linux_Build'
          pool:
            vmImage: 'ubuntu-18.04'
          os: 'linux'

      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Mac_Build'
          pool:
            vmImage: 'macos-10.14'
          os: 'darwin'

      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Windows_Build'
          pool:
            vmImage: 'windows-2019'

  - stage: Test
    jobs:
      - template: templates/azure/jobs/test.yml

  - stage: Release
    jobs:
      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Linux_Release'
          pool:
            vmImage: 'ubuntu-18.04'
          os: 'linux'

      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Mac_Release'
          pool:
            vmImage: 'macos-10.14'
          os: 'darwin'

      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Windows_Release'
          pool:
            vmImage: 'windows-2019'
