# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master
  - dev
  - release/*
  - feature/*
  - hotfix/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macos-10.14'
#    windows:
#      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - task: GoTool@0
    displayName: 'Use Go 1.14'
    inputs:
      version: '1.14'

  - script: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
      $(go env GOPATH)/bin/golangci-lint run
    displayName: 'Run Code Quality Checks'

  - script: |
      curl https://cdn.shiftleft.io/download/sl > $BUILD_SOURCESDIRECTORY/sl && chmod a+rx $BUILD_SOURCESDIRECTORY/sl
      $BUILD_SOURCESDIRECTORY/sl analyze --app MyLabs-G0 --cpg --go ./...
      sleep 10
    displayName: 'Run Vulnerability Checks'
    env:
      SHIFTLEFT_ORG_ID: $(SHIFTLEFT_ORG_ID)
      SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)

  - task: Go@0
    displayName: 'Run Unit Tests'
    inputs:
      command: 'test'
      arguments: '-v ./...'

  - task: Go@0
    displayName: 'Build'
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      arguments: '-o $(Build.BinariesDirectory)/mylabs-go'

  - task: CopyFiles@2
    displayName: 'Copy binary files to Artifact Stage Directory'
    inputs:
      sourceFolder: $(Build.BinariesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      artifactName: mylabs-go
