# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - release/*
      - feature/*
      - hotfix/*
      - bugfix/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

variables:
  APPNAME: mylabs-go
  major: 0
  minor: 5
  PATCHVER: $(Rev:.r)
  GOPATH: '$(Pipeline.Workspace)/gowork'

name: $(major).$(minor)$(Rev:.r)

stages:
  - stage: Build
    jobs:
      - template: templates/azure/jobs/build.yml
        parameters:
          appName: $(APPNAME)
          name: 'Linux_Build'
          pool:
            vmImage: 'ubuntu-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)

      - template: templates/azure/jobs/build.yml
        parameters:
          appName: $(APPNAME)
          name: 'Mac_Build'
          pool:
            vmImage: 'macos-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)

      - template: templates/azure/jobs/build.yml
        parameters:
          appName: $(APPNAME)
          name: 'Windows_Build'
          pool:
            vmImage: 'windows-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)

  - stage: Test
    jobs:
      - template: templates/azure/jobs/test.yml

  - stage: Release
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hostfix'))
    jobs:
      - template: templates/azure/jobs/release.yml
        parameters:
          appName: $(APPNAME)
          name: 'Linux_Release'
          pool:
            vmImage: 'ubuntu-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)

      - template: templates/azure/jobs/release.yml
        parameters:
          appName: $(APPNAME)
          name: 'Mac_Release'
          pool:
            vmImage: 'macos-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)

      - template: templates/azure/jobs/release.yml
        parameters:
          appName: $(APPNAME)
          name: 'Windows_Release'
          pool:
            vmImage: 'windows-latest'
          majorVer: $(MAJORVER)
          minorVer: $(MINORVER)
          patchVer: $(PATCHVER)
