# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

pr:
  autoCancel: false
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - LICENSE
      - .travis.yml
      - .github/*
      - .gitignore

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gowork'

stages:
  - stage: Build
    jobs:
      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Linux Build'
          pool:
            vmImage: 'ubuntu-18.04'
      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Mac Build'
          pool:
            vmImage: 'macos-10.14'
      - template: templates/azure/jobs/build.yml
        parameters:
          name: 'Windows Build'
          pool:
            vmImage: 'vs2017-win2016'

  - stage: Test
    jobs:
      - template: templates/azure/jobs/test.yml

  - stage: Release
    jobs:
      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Linux Build'
          pool:
            vmImage: 'ubuntu-18.04'
      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Mac Build'
          pool:
            vmImage: 'macos-10.14'
      - template: templates/azure/jobs/release.yml
        parameters:
          name: 'Windows Build'
          pool:
            vmImage: 'vs2017-win2016'
