parameters:
  appName: ''

jobs:
  - job:
    strategy:
      matrix:
        linux:
          vmImage: 'ubuntu-latest'
        mac:
          vmImage: 'macos-latest'
        windows:
          vmImage: 'windows-latest'

    pool:
      vmImage: $(vmImage)

    steps:
      - template: ../steps/setupgo.yml

      - template: ../steps/buildapp.yml
        parameters:
          appName: ${{ parameters.appName }}

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs:
          artifactName: $(Agent.OS)
