parameters:
  name: ''
  pool: ''
  appName: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - template: ../steps/setupgo.yml

      - template: ../steps/buildapp.yml
        parameters:
          appName: ${{ parameters.appName }}
