parameters:
  name: ''
  pool: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - task: GoTool@0
        displayName: 'Use Go 1.14'
        inputs:
          version: '1.14'

      - task: Go@0
        displayName: 'Build Application Binary'
        inputs:
          command: 'build'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          arguments: '-o $(Build.BinariesDirectory)/mylabs-go'
