parameters:
  name: ''
  pool: ''
  os: 'linux'

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - template: ../steps/setupgo.yml

      - template: ../steps/buildapp.yml
        parameters:
          binDirectory: $(Build.BinariesDirectory)
          os: ${{ parameters.os }}
