parameters:
  name: ''
  pool: ''
  os: 'linux'

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - template: ../steps/setupgo.yml

      - template: ../steps/buildapp.yml
        parameters:
          binDirectory: $(Build.BinariesDirectory)

      - task: CopyFiles@2
        displayName: 'Copy binary files to Artifact Stage Directory'
        inputs:
          sourceFolder: $(Build.BinariesDirectory)
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs:
          artifactName: $(parameters.os)

      - task: Bash@3
        displayName: 'Get/Set Application/Package Version'
        inputs:
          targetType: 'inline'
          script: |
            set -e -x
            if [ $(parameters.os) == 'windows' ]; then
              version=`./mylabs-go.exe version`
            else
              version=`./mylabs-go version`
            fi
            echo "##vso[task.setvariable variable=MYLABSCLI_VERSION;]$version"
          workingDirectory: $(Build.BinariesDirectory)

      - task: UniversalPackages@0
        displayName: 'Publish Release Artifacts'
        inputs:
          command: 'publish'
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          feedsToUsePublish: 'internal'
          vstsFeedPublish: '1354bdaa-1b77-41d3-a573-e85080e85d85/90f9f1a3-3b7f-4814-aea6-f06d7842d9af'
          vstsFeedPackagePublish: $(parameters.os)
          versionOption: 'custom'
          versionPublish: $(MYLABSCLI_VERSION)
